### ISSUE TITLE
Trailing backslash in COPY Gemfile command

### ISSUE THREAD

**Issue by geneorama** [srobbin/sweeparoundus#2]
https://github.com/srobbin/sweeparoundus/blob/32a11476cf63ad55399ac085c72fce897bf2069c/Dockerfile#L12

For some reason I get an error when building the Dockerfile unless I change the line above to `COPY Gemfile* ./` (with the trailing backslash). I'm not sure why that matters or if I'm doing something wrong? 

I was just testing to see if I could get a demonstration version running in AWS.

**Comment by srobbin** [comment]
@geneorama Your syntax looks better than mine. I just merged in PR #3, which doesn't make the change you mentioned above, directly, but should effectively help bypass Gemfile issues and get you up and running with 2023 data. Let me know if you run into any troubles.
